# Note: Do not change these following values to match with your environment.
# Create a new `config.override.yaml` to merge the config instead.

app:
  env: local # E.g. local, staging, production.
  redirectUrl: "https://irving.dev"

http:
  port: 8000

database:
  uri: "mongodb://127.0.0.1:27017"
  name: "osgarth"
